enum EnvNames {
  BASE_URL = "BASE_URL",
  DENO_ENV = "DENO_ENV",
  GITHUB_CLIENT_ID = "GITHUB_CLIENT_ID",
  GITHUB_CLIENT_SECRET = "GITHUB_CLIENT_SECRET",
  DATABASE_URL = "DATABASE_URL",
}

export default EnvNames;
