// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/api/users.ts";
import * as $2 from "./routes/auth/[provider]/callback.tsx";
import * as $3 from "./routes/auth/[provider]/index.tsx";
import * as $4 from "./routes/dashboard/_middleware.ts";
import * as $5 from "./routes/dashboard/index.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/logout.ts";
import * as $$0 from "./islands/BarChartContainer.tsx";
import * as $$1 from "./islands/DoughnutChartContainer.tsx";
import * as $$2 from "./islands/LineChartContainer.tsx";
import * as $$3 from "./islands/PieChartContainer.tsx";
import * as $$4 from "./islands/UserAvatarButton.tsx";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/api/users.ts": $1,
    "./routes/auth/[provider]/callback.tsx": $2,
    "./routes/auth/[provider]/index.tsx": $3,
    "./routes/dashboard/_middleware.ts": $4,
    "./routes/dashboard/index.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/logout.ts": $7,
  },
  islands: {
    "./islands/BarChartContainer.tsx": $$0,
    "./islands/DoughnutChartContainer.tsx": $$1,
    "./islands/LineChartContainer.tsx": $$2,
    "./islands/PieChartContainer.tsx": $$3,
    "./islands/UserAvatarButton.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
